// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

namespace WebApplication1.Migrations.Despesas
{
    [DbContext(typeof(DespesasContext))]
    partial class DespesasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.despesas", b =>
                {
                    b.Property<int>("DespID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Agua")
                        .HasColumnType("float");

                    b.Property<double>("Aluguel")
                        .HasColumnType("float");

                    b.Property<double>("Internet")
                        .HasColumnType("float");

                    b.Property<double>("Luz")
                        .HasColumnType("float");

                    b.Property<double>("Materiais")
                        .HasColumnType("float");

                    b.Property<double>("Pagamentos")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Telefone")
                        .HasColumnType("float");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DespID");

                    b.ToTable("Despesas");
                });
#pragma warning restore 612, 618
        }
    }
}
